version: "3.8"

services:
  tensorflow:
    image: ystsai7981/tensorflow:latest
    volumes:
      - ~/tensorflow:/home/ystsai/work
    ports:
      - "8895:8888"
      - "6006:6006"
    container_name: tf
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
